// SPRINT-111 / TASK-11102 — the typed-read trust boundary.
//
// The OpenAPI spec (docs/api/openapi.json, generated by TASK-11101) is the source
// of the response types in `api-types.ts`. Two facts about that spec shape the
// helpers here:
//
//   1. It declares NO `required` arrays → every generated property is OPTIONAL
//      (`field?: T`). The FE's hand-written hook interfaces are STRICT (required
//      fields, used as such by ~26 downstream files), so the generated shape is
//      not directly assignable to them.
//   2. Danish unit-type / org-type / period-status enums serialize as plain
//      `string` (the C# properties are `string`), so the generated type is wider
//      than the FE's literal unions (`UnitType`, `'MAO'`, `'OPEN' | …`).
//
// `coerceApiResponse` bridges that variance for the `setState` assignment. It is
// the SINGLE assertion in the typed-read path and lives HERE — out of the four
// no-`as` hook files — paired with the compile-time `AssertFieldsInSpec` guard
// below so the coercion is provably field-name-safe, not an `as any` escape:
//
//   * `AssertFieldsInSpec<Local, SpecKey>` fails `tsc` when the FE's strict
//     interface reads a field that is NOT present in the spec schema (a
//     renamed / removed backend field — the S97→S99→S100 "fetchEnheder" drift
//     class — caught at build). Additive spec fields are allowed (subset, not
//     equality), matching the PAT-010 "required-field presence" philosophy.
//   * The TASK-11101 per-route spec≡runtime gate guarantees the spec ≡ the real
//     serialized bytes. So: (FE fields ⊆ spec fields) ∧ (spec ≡ runtime) ⇒ the FE
//     reads only fields the server actually sends. The coercion only re-narrows
//     optionality + the string→literal enum variance.

import type { components } from './api-types'

type Schemas = components['schemas']

/** Resolves to `true` only when every key of the FE-strict `Local` interface is a
    key of the OpenAPI schema `SpecKey`; otherwise resolves to a branded object
    naming the offending FE field(s) so the `tsc` error is self-describing. */
export type AssertFieldsInSpec<Local, SpecKey extends keyof Schemas> = [
  Exclude<keyof Local, keyof Schemas[SpecKey]>,
] extends [never]
  ? true
  : {
      __FE_FIELD_MISSING_FROM_OPENAPI_SPEC__: Exclude<keyof Local, keyof Schemas[SpecKey]>
    }

/** Compile-time assertion anchor — `Assert<T>` is only well-formed when `T` is
    `true`, so `type _ = Assert<AssertFieldsInSpec<…>>` errors on drift. */
export type Assert<T extends true> = T

/**
 * Coerce a spec-typed (all-optional, string-enum) response value to the FE's
 * strict literal-typed view. Safe ONLY when paired with an `AssertFieldsInSpec`
 * guard on the target type (see this module's header) — it bridges optionality
 * and enum-literal variance, NOT field identity. The envelope key the value is
 * read from (`result.data.forest`, `…units`, …) is type-checked at the call site
 * BEFORE coercion, so a renamed envelope key is a `tsc` error there.
 */
export function coerceApiResponse<T>(value: unknown): T {
  return value as T
}
